-- AlterTable
ALTER TABLE "Test" ALTER COLUMN "testInput" SET NOT NULL,
ALTER COLUMN "testInput" SET DATA TYPE TEXT,
ALTER COLUMN "testOutput" SET NOT NULL,
ALTER COLUMN "testOutput" SET DATA TYPE TEXT;
